# Site settings
title: Zatourie
motto: Carpe diem
email: minkyu.shim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Study 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zatourie.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  zatourie

# Build settings
markdown: kramdown
